// USER ACTION TYPES
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

// CHAT ACTION TYPES
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const SET_PRIVATE_CHAT = 'SET_PRIVATE_CHAT';
export const CLEAR_CHAT = 'CLEAR_CHAT';

// COLOR ACTION TYPES
export const SET_THEME = 'SET_THEME';
export const CLEAR_THEME = 'CLEAR_THEME';
